### PR TITLE
Skate over SkateJS for titles.

### PR DESCRIPTION
**Pull request by TravisTheTechie**
Fixes https://github.com/skatejs/skatejs/issues/237

### CODE REVIEW

**Comment by treshugart** [comment]
Sorry for this not being obvious :( but the docs are hosted on the actual gh repo so they can be easily versioned and deployed from the project. Docs are also using a static site generator, so the file you'll probably want to update is: https://github.com/skatejs/skatejs/blob/0.13.x/docs/templates/layout.html.

**Comment by TravisTheTechie** [comment]
So this repo is... nothing?

**Comment by treshugart** [comment]
This repo exists so that github can serve it at skatejs.github.io. skate.js.org actually serves from here.

**Comment by treshugart** [comment]
Docs have diverged between what was here and what was on 0.13.x unfortunately. Merging this. Master will be the new docs once the next version is released.

**Pull request merged**
